apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: "6.*"
    helm:
      values: |
        replicaCount: 2
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: demo.192-64-84-66.sslip.io
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: podinfo-gitops-tls
              hosts:
                - demo.192-64-84-66.sslip.io
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
